// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsyddlnrueucecnvsfwx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzeWRkbG5ydWV1Y2VjbnZzZnd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NTg4NzIsImV4cCI6MjA2NjQzNDg3Mn0.TNmDqRHSNXQTwPfUlKYMbd-Uu--4q4qlQowSEm4kTUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);