// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulmizpkzvgipgiblfzsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsbWl6cGt6dmdpcGdpYmxmenNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NTcxNDEsImV4cCI6MjA2NjQzMzE0MX0.056K_-RUh3fIxKxDMPn6mDvVs2GSp2nE1nUt2yVYvkM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);